# Assignment 1

## Machine Learning 1 - Evaluation Metrics

**Utkarsh Thusoo**  
**M20AIE318**

**Q1. Explain any three new evaluation metrics (other than discussed in class) with
proper explanation and analysis.**

**Answer:**

Most of the Evaluation matrix used in Classification model covered in class are:

1. Accuracy
2. Precision
3. Recall
4. F1 score
5. AUC-ROC curve
6. CMC

Below are list of additional matrices which can be used:

1. **F Beta Score**
    
    Its a measure which helps us balance precision and recall. 

    $$
      Precision = \frac{TruePositives}{TruePositives + FalsePositives}\
    $$
    
    $$
      Recall = \frac{TruePositives}{TruePositives + FalseNegatives}\
    $$
    
    As we know our goal is always to reduce the `FalsePositives` and `FalseNegatives`. F-Beta provides a balance between `FalsePositives` and `FalseNegatives`.

    $$
      F_{beta} = \frac{(1 + beta^2) * Precision * Recall}{beta^2 * Precision + Recall}\
    $$

    From formule we can clearly identify that beta is taken into account with Precision which deals with FalsePositive. Hence when we want to put more weight on FalsePositive(i.e Precision) than on FalseNegative we can use a smaller beta value (beta < 1 and when we want more weight to be given to FalseNegative (i.e Recall), we can use a greater value (beta > 1). If we want a balanced value between precision and call we can use beta value as 1.
    
    #### Rules and Examples:
    
    ##### A. **$F_{0.5}-Measure (beta=0.5)$:**
    
    $F_{0.5}$-measure puts more attention on minimizing false positives than minimizing false negatives. 
    
    ex. _In case of spam check, we want very low false positives because if regular mail is reported as spam, user might lose important information hence we can more focus on precision._    
    
   ##### B. $F_{2.0}-Measure (beta=2.0)$:
    
    $F_{2.0}$-measure puts less weight on precision, more weight on recall.
    
    ex. _In case of airport we don't want any dangerous items to be boarded into a flight. Hence we want to reduce falseNegatives putting more value on Recall._
    
   #### Compariosion of F 0.5, F1 & F2:
    
    Suppose for below scenarios where we have perfect precision and 50% recall.  
    **Precision = 1.0**  
    **Recall = 0.5**  
      
   ##### A. If Beta = 1
    - F1-Measure = ((1 + 1^2) * Precision * Recall) / (1^2 * Precision + Recall)
    - F1-Measure = (2 * 1.0 * 0.5) / ( 1.0 + 0.5 )
    - F1-Measure = 1.0 / 1.5
    - F1-Measure = 0.666  
    
   ##### B. If Beta = 0.5
    - F0.5-Measure = ((1 + 0.5^2) * Precision * Recall) / (0.5^2 * Precision + Recall)
    - F0.5-Measure = (1.25 * Precision * Recall) / (0.25 * Precision + Recall)
    - F0.5-Measure = (1.25 * 1.0 * 0.5) / (0.25 * 1.0 + 0.5)
    - F0.5-Measure = 0.625 /0.75
    - F0.5-Measure = 0.833
    
    _As in Beta < 1 we want to provide more weightage to the Precision, we can clearly see a higher precision score of 0.83 which is much more than the normal F1 score. We are not getting penalized for the low recall._
    
   ##### C. If Beta = 2.0
    - F2-Measure = ((1 + 2^2) * Precision * Recall) / (2^2 * Precision + Recall)
    - F2-Measure = (5 * Precision * Recall) / (4 * Precision + Recall)
    - F2-Measure = (5 * 1.0 * 0.5) / (4 * 1.0 + 0.5)
    - F2-Measure = 2.5 /4.5
    - F2-Measure = 0.555
    
    _As in Beta > 1 we want to provide more weightage to the Recall, we can clearly see a lower score of 0.555 which is much less than the normal F1 score. We are getting penalized for the low recall value._

 2. **Cohen Kappa**
 
    When we compute accuracy we don't take into account the random chance which lead to the model predict correct values. As this random hits can be further taken into account to compute accuracy we can use kappa score to handle these scenarios. Cohen Kappa is particularly useful when the target class is unbalanced which leads to overall accuracy being biased.

    Inititally introduced to measure aggrement between observers of psychological behavior it's actually intended to measure the degree of agreement, or disagreement, between two people which are observing a same experiment. Cohens kappa has universal range from -1 to +1. Postive one indicates strong aggrement or a perfect model, negative corresponds to a strong disagreement while zero indicates chance-level aggrement.
    
    #### Cohen's Kappa for binary distriution
    
    Let us try to explain this with an example. Customer with good rating represent 90% of the data and customer with bad rating represent 10% of the data. A classification model that predicts a rating of all customers as good would reach an accuracy of as high as 90%. Cohen's Kappa tries to correct this bias by taking into account the priori distribution.
    
    $$
        \kappa = \frac{P_o - P_e}{1 - P_e}
    $$
    
    - $P_o$: Overall accuracy of the model i.e. is the proportion of observed agreement  
    - $P_e$: Overall accuracy that can be reached with a random guess i.e. the Expected Accuracy, the level of Accuracy we expect to obtain by chance.  
    - $1 - P_e$: is the maximum value of this difference as give by a perfect model with accuracy of 100%
    
    To calucate overall accuracy for a random guess $P_e$, we make a strong assumption that the model predictions are not affected by the priori distribution of the target class. This assumption is often violated when working with unbalanced data since the classification model tends to predict the majority class in case of uncertinity.

    However be caeful when you compare cohen kappa values between models, because cohen's kappa tends to be higher when the target classes are balanced. Cohen's Kappa is not informative about expected prediction accuracy. The interpretation of cohen's Kappa alues in terms like "moderate" is neither easy not fixed.
    
    #### Cohen's Kappa for multiclass distriution

    || <div style="width:150px">C1</div> | <div style="width:150px">C2</div> | <div style="width:150px">C3</div> | <div style="width:150px">Total</div> |
    | :- | :- | :- | :- | :- |
    |**C1**| a | b | c | $a+b+c=C1_{corr}$ |
    |**C2**| d | e | f | $d+e+f=C2_{corr}$ |
    |**C3**| g | h | i | $g+h+i=C3_{corr}$ |
    |**Total**|$a+d+g=C1_{pred}$|$b+e+h=C3_{pred}$ |$c+f+i=C3_{pred}$ |$N$|

    Being N the total number of patterns, C1, C2 and C3 the label related with class 1,2 or 3, respectively. Their Cohen’s kappa is given by:  
    
    $$
      Cohne's Kappa = \frac{N * (a + e + i) - (C1_{corr} * C1_{pred} + C2_{corr} * C2_{pred} + C2_{corr} * C2_{pred})}{N^2 - (C1_{corr} * C1_{pred} + C2_{corr} * C2_{pred} + C2_{corr} * C2_{pred})}\
    $$
    
    It can be generalized to the _m_ classes where $CM_{ii}$ represent the diagonal elements of the confusion matrix.
    
    $$
       Cohne's Kappa = \frac{N\sum_{i=1}^{m} CM_{ii} \sum_{i=1}^{m} Ci_{corr}Ci_{pred}}{N^2 - \sum_{i=1}^{m} Ci_{corr}Ci_{pred}}
    $$

 3. **Mattheus Correlation Coefficient (MCC)**
     
     MCC is a tool for model evaluation. It measures the differences between actual values and predicted values and is equivalent to the chi-square statistic for a 2 x 2 contingency table.
     
     MCC is generally regarded as a balanced measure which can be used in binary classification even if the classes are very different in size. The coefficient takes into account true negatives, true positives, false negatives and false positives. This reliable measure produces high scores only if the prediction returns good rates for all four of these categories.
     
     Like most correlation coefficients, MCC ranges between -1 and 1:
    - 1 is the best agreement between actuals and predictions,
    - zero is no agreement at all. In other words, the prediction is random with respect to actuals.
    
    #### MCC for binary distriution
    
    As MCC takes into account full confusion matrix below is the formulae for the same.
    
    $$
      MCC = \frac{TP * TN - FP * FN}{\sqrt{(TP + FP)(TP + FP)(TN + FN)(TN + FP)}}
    $$
    
    ##### Example:
    
    Imagine we have a classifier that is trying to differenciate between cats and dogs by identifying them based on their images. Below is the confusion matrix:
    
    || Cat | Dog |  |
    | --- | --- | --- | --- |
    |**Cat**| 109 | 1 | 110 |
    |**Dog**| 9 | 1 | 10 |
    || 118 | 2 | 120 |
    
    We can see we have predicted only 1 out of 10 dog correctly while 109 cats were correctly identified.
    
    ##### Scenario 1: 
    - cats are positive  
    - dogs are negative
    
    | Evaluation Matrix | Value | 
    | :- | -: |
    | **Accuracy** | (109 + 1)/ 120 = 0.92 |
    | **Precision** | 109/ (109+9) = 0.92 |
    | **Recall** | 109/ (109+1) = 0.99  |
    | **F1 Score** | 0.95  |
    
    ##### Scenario 2: 
    - cats are negative  
    - dogs are positive
 
     | Evaluation Matrix | Value | 
    | :- | -: |
    | **Accuracy** | (109 + 1)/ 120 = 0.92 |
    | **Precision** | 1/ (1+1) = 0.50 |
    | **Recall** | 1/ (9+1) = 0.10  |
    | **F1 Score** | 0.16  |

    F1 score does not take into account TN at all which is the reason of this drop in percentage.
    
    Using MCC formule we get a value **MCC = 0.21**. MCC has a low value which suggests that even with a high positive class results it still gave us poor score because our negative class was not well predicted (1 out of 10 was predicted correctly).
   
    #### MCC for Multi-class Classification
    
    the True and the Predicted class distributions are no longer binary and a higher number of classes has been taken into account. In this case numerator and denominator take a different shape compared to the binary case and this can partially help to find more stable results inside the range [-1;+1] of MCC.
    
    $$
      MCC = \frac{c * s \sum_{k}^{K} p_{k} * t_{k}}{\sqrt{(s^2 - \sum_{k}^{K} p_{k}^2)(s^2 - \sum_{k}^{K} t_{k}^2)}}
    $$
    
    To simplify the definition, it is necessary to consider the following intermediate variables
    
    - $ c = \sum_{k}^{K} C_{kk}$ the total number of elements correctly predicted
    - $ s = \sum_{i}^{K} \sum_{j}^{K} C_{ij}$ the total number of elements
    - $ p_{k} = \sum_{i}^{K} C_{ki}$ the number of times that class k was predicted (column total)
    - $ t_{k} = \sum_{i}^{K} C_{ik}$ the number of times that class k truly occurred (row total)

**Question 2: Evaluate the performance of the predictions using different evaluation metrics:Do not use any predefined library for calculating a. to e. All the evaluation should be done from scratch.**

**1. Calculate overall accuracy and class-wise accuracy.**  
**2. Calculate confusion metrics.**  
**3. Calculate precision and recall for all classes and report macro average and weighted average values.**  
**4. calculate F1 score for all classes.**  
**5. Report Type-1 and Type-II error for given data.**  
**6. Draw a comparison table between above determined values and values observed from sklearn library (predefined library for performance evaluation).**  
**7. Use any 2 metrics from Question 1 for implementation and report your results for this dataset.**  


## Manual Computation

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("dataset.xlsx")
print(df)

     Predicted Class  Actual Class
0                  0             0
1                  0             0
2                  1             0
3                  0             0
4                  0             0
..               ...           ...
155                3             3
156                3             3
157                3             3
158                2             3
159                0             3

[160 rows x 2 columns]


In [2]:
total_class = df["Predicted Class"].unique().size
print("Total Distinct classes:", total_class)


def printValues(header, values):
    
    if isinstance(values, np.ndarray):
        print('\033[1m%s: \033[0m' % (header))
        
        for each in range(0, total_class):
            if isinstance(values[each], np.float64):
                print("Class %d: %f" % (each, values[each]))
            elif isinstance(values[each], np.int64):  
                print("Class %d: %d" % (each, values[each]))
    else:
        print('\033[1m%s: \033[0m %s' % (header, values))

Total Distinct classes: 4


In [3]:
manual_cf_matrix = np.zeros([total_class, total_class], dtype = int) 

for i in range(len(df)) : 
    np.add.at(manual_cf_matrix[df.iloc[i, 1]], df.iloc[i, 0], 1)

print('\033[1m' + 'Confusion Matrix:' + '\033[0m')
print(manual_cf_matrix)

Confusion Matrix:
[[33  8  4  4]
 [ 1 32  3  0]
 [ 3  2 29  6]
 [ 2  3  3 27]]


In [4]:
actual_cases = np.sum(manual_cf_matrix, axis = 1)
printValues("Actual Class", actual_cases)

predicted_cases = np.sum(manual_cf_matrix, axis = 0)
printValues("Predicted Class", predicted_cases)

Actual Class: 
Class 0: 49
Class 1: 36
Class 2: 40
Class 3: 35
Predicted Class: 
Class 0: 39
Class 1: 45
Class 2: 39
Class 3: 37


In [5]:
fn_cases = np.zeros([total_class], dtype = int) 
tp_cases = np.zeros([total_class], dtype = int) 

for row in range(0, total_class):
    sum = 0
    for column in range(0, total_class):
        if(row == column):
            tp_cases[row] = manual_cf_matrix[row][column] 
            continue
        sum = sum + manual_cf_matrix[row][column]    
    fn_cases[row] = sum        

printValues("True Positive Cases", tp_cases)
printValues("False Negative Cases", fn_cases)

True Positive Cases: 
Class 0: 33
Class 1: 32
Class 2: 29
Class 3: 27
False Negative Cases: 
Class 0: 16
Class 1: 4
Class 2: 11
Class 3: 8


In [6]:
fp_cases = predicted_cases - tp_cases
printValues("False Positive Cases", fn_cases)

tn_cases = actual_cases.sum() - (actual_cases + fn_cases)
printValues("True Negative Cases", fn_cases)

False Positive Cases: 
Class 0: 16
Class 1: 4
Class 2: 11
Class 3: 8
True Negative Cases: 
Class 0: 16
Class 1: 4
Class 2: 11
Class 3: 8


In [7]:
tnr = tn_cases / (fp_cases + tn_cases)
tpr = tp_cases / (fn_cases + tp_cases)

printValues("True Positive Rate", tpr)
printValues("True Negative Rate", tnr)

True Positive Rate: 
Class 0: 0.673469
Class 1: 0.888889
Class 2: 0.725000
Class 3: 0.771429
True Negative Rate: 
Class 0: 0.940594
Class 1: 0.902256
Class 2: 0.915966
Class 3: 0.921260


In [8]:
class_accuracy = ( tpr + tnr ) / 2 
printValues("Accuracy", class_accuracy)

Accuracy: 
Class 0: 0.807032
Class 1: 0.895572
Class 2: 0.820483
Class 3: 0.846344


In [9]:
overall_accuracy = tp_cases.sum() / actual_cases.sum()
printValues("Accuracy", overall_accuracy)

Accuracy:  0.75625


In [10]:
precision = tp_cases / ( tp_cases + fp_cases )
printValues("Precision", precision)

Precision: 
Class 0: 0.846154
Class 1: 0.711111
Class 2: 0.743590
Class 3: 0.729730


In [11]:
macro_precision = precision.sum() / precision.size
printValues("Macro Precision", macro_precision)

Macro Precision:  0.7576461076461076


In [12]:
micro_precision = tp_cases.sum() / (tp_cases.sum() + fp_cases.sum())
printValues("Micro Precision", micro_precision)

Micro Precision:  0.75625


In [13]:
weighted_average_precision = ((actual_cases / actual_cases.sum()) * precision).sum()
printValues("Weighted Avergae Precision", weighted_average_precision)

Weighted Avergae Precision:  0.7646604296604297


In [14]:
recall = tp_cases / ( tp_cases + fn_cases )
printValues("Recall", recall)

Recall: 
Class 0: 0.673469
Class 1: 0.888889
Class 2: 0.725000
Class 3: 0.771429


In [15]:
macro_recall = recall.sum() / recall.size
printValues("Macro Recall", macro_recall)

Macro Recall:  0.7646967120181406


In [16]:
weighted_average_recall = ((actual_cases / actual_cases.sum()) * recall).sum()
printValues("Weighted Avergae Recall", weighted_average_recall)

Weighted Avergae Recall:  0.7562500000000001


In [17]:
f05 = ((1 + 0.5 ** 2) * precision * recall) / ((0.5 ** 2 * precision) + recall)
printValues("F0.5 Measure", f05)

F0.5 Measure: 
Class 0: 0.804878
Class 1: 0.740741
Class 2: 0.739796
Class 3: 0.737705


In [18]:
f1 = 2 / (1 / precision + 1 / recall)
printValues("F1 Measure", f1)

F1 Measure: 
Class 0: 0.750000
Class 1: 0.790123
Class 2: 0.734177
Class 3: 0.750000


In [19]:
f2 = ((1 + 2 ** 2) * precision * recall) / ((2 ** 2 * precision) + recall)
printValues("F2.0 Measure", f2)

F2.0 Measure: 
Class 0: 0.702128
Class 1: 0.846561
Class 2: 0.728643
Class 3: 0.762712


In [20]:
weighted_average_f1 = ((actual_cases / actual_cases.sum()) * f1).sum()
printValues("Weighted Avergae F1", weighted_average_f1)

Weighted Avergae F1:  0.7550720815752461


In [21]:
macro_average_f1 = f1.sum() / f1.size
printValues("Macro Avergae F1", macro_average_f1)

Macro Avergae F1:  0.7560751679949992


In [22]:
fpr = fp_cases / ( tn_cases + fp_cases )
fnr = fn_cases / ( fn_cases + tp_cases )

printValues("Type 1 Error", fpr)
printValues("Type 2 Error", fnr)

Type 1 Error: 
Class 0: 0.059406
Class 1: 0.097744
Class 2: 0.084034
Class 3: 0.078740
Type 2 Error: 
Class 0: 0.326531
Class 1: 0.111111
Class 2: 0.275000
Class 3: 0.228571


In [23]:
class_sum = (actual_cases * predicted_cases).sum()

kappa_value = ((actual_cases.sum() * tp_cases.sum()) - class_sum) / ((actual_cases.sum() ** 2) - class_sum) 
printValues("Kappa Value", kappa_value)

Kappa Value:  0.6752368064952639


## Sckikit Values

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_curve
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

sklearn_cf_matrix = confusion_matrix(df['Actual Class'], df['Predicted Class'])
sklearn_kappa_vaue = cohen_kappa_score(df['Actual Class'], df['Predicted Class'])
sklearn_accuracy = accuracy_score(df['Actual Class'], df['Predicted Class'])
sklearn_macro_precision = precision_score(df['Actual Class'], df['Predicted Class'], average='macro')
sklearn_weighted_precision = precision_score(df['Actual Class'], df['Predicted Class'], average='weighted')
sklearn_macro_recall = recall_score(df['Actual Class'], df['Predicted Class'], average='macro')
sklearn_weighted_recall = recall_score(df['Actual Class'], df['Predicted Class'], average='weighted')
sklearn_macro_f1 = f1_score(df['Actual Class'], df['Predicted Class'], average='macro')
sklearn_weighted_f1 = f1_score(df['Actual Class'], df['Predicted Class'], average='weighted')
sklearn_report = classification_report(df['Actual Class'], df['Predicted Class'], target_names=['Class 0' , 'Class 1', 'Class 2', 'Class 3'])

## Consolidated Values:

#### For manual computation matrices to be chosen from question 1, I have used FBeta (F0.5 & F2) and Cohen Kappa for analysis.

In [25]:
print('\033[1m' + 'Manual Confusion Matrix:' + '\033[0m')
print(manual_cf_matrix)

print('\033[1m' + 'Sklearn Confusion Matrix:' + '\033[0m')
print(sklearn_cf_matrix)

Manual Confusion Matrix:
[[33  8  4  4]
 [ 1 32  3  0]
 [ 3  2 29  6]
 [ 2  3  3 27]]
Sklearn Confusion Matrix:
[[33  8  4  4]
 [ 1 32  3  0]
 [ 3  2 29  6]
 [ 2  3  3 27]]


In [26]:
highlevel_df = pd.DataFrame([["Accuracy", overall_accuracy, sklearn_accuracy], 
                             ["Macro Precision", macro_precision, sklearn_macro_precision], 
                             ["Cohen Kappa", kappa_value, sklearn_kappa_vaue],
                             ["Weighted Avergae Precision", weighted_average_precision, sklearn_weighted_precision],
                             ["Macro Avergae Precision", macro_precision, sklearn_macro_precision],
                             ["Weighted Avergae Recall", weighted_average_recall, sklearn_weighted_recall],
                             ["Macro Avergae Recall", macro_recall, sklearn_macro_recall],
                             ["Weighted Avergae F1", weighted_average_f1, sklearn_weighted_f1],
                             ["Macro Avergae F1", macro_average_f1, sklearn_macro_f1],
                            ],
                columns=['Evaluation Matrix', 'Manual Values', 'Skilearn Values'])

highlevel_df.style.hide_index().set_properties(**{'text-align': 'left'})

In [27]:
print('\033[1m' + 'Manual high level report:' + '\033[0m')

basic_df = pd.DataFrame(np.array(
                    [actual_cases, predicted_cases, tp_cases, fp_cases, tn_cases, fn_cases]),
                columns=['Class 0', 'Class 1', 'Class 3', 'Class 4'],
                index = ['Actual Cases', 'Total Samples', 'TP', 'FP' , 'TN', 'FN'])

basic_df.style.set_properties(**{'text-align': 'right'})



Manual high level report:


In [28]:
print('\033[1m' + 'Manual rate computations report:' + '\033[0m')

rate_df = pd.DataFrame(np.array(
                    [ tpr, tnr, fpr, fnr, precision, recall, f1, f05, f2]),
                columns=['Class 0', 'Class 1', 'Class 3', 'Class 4'],
                index = ['TPR', 'TNR', 'Type 1 Error', 'Type 2 Error','Precision', 'Recall', 'F1', 'F0.5', 'F2'])

rate_df.style.set_properties(**{'text-align': 'right'})

Manual rate computations report:


In [29]:
print('\033[1m' + 'Consolidated scikit report:' + '\033[0m')
print(sklearn_report)

Consolidated scikit report:
              precision    recall  f1-score   support

     Class 0       0.85      0.67      0.75        49
     Class 1       0.71      0.89      0.79        36
     Class 2       0.74      0.72      0.73        40
     Class 3       0.73      0.77      0.75        35

    accuracy                           0.76       160
   macro avg       0.76      0.76      0.76       160
weighted avg       0.76      0.76      0.76       160

